spring:
  datasource:
    url: jdbc:mysql://120.55.55.185:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不访问这些数据
      stat-view-servlet:
        login-username: druid
        login-password: druid

