server:
  port: 8080

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://120.55.55.185:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    #阿里druid连接池
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true

mybatis:
  #mapper文件路径配置
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml